apiVersion: v1
kind: Secret
metadata:
  name: student-management-secret
  namespace: devops
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UGFzc3dvcmQxMjM=   # "Password123" encodé en Base64
  MYSQL_USER: dXNlcg==                     # "user" encodé en Base64
  MYSQL_PASSWORD: cGFzc3dvcmQ=             # "passw0rd" encodé en Base64
