apiVersion: v1
kind: Service
metadata:
  name: student-management-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: student-management
  ports:
    - port: 8080         # port interne du service
      targetPort: 8080   # port du container
      nodePort: 30081    # port expos√© sur le noeud
